name: sistem_rekomendasi_wisata_maluku
description: A recommendation app for Maluku tourism (demo)
publish_to: 'none'
version: 1.0.0+1



environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  shared_preferences: ^2.1.1
  intl: ^0.18.0

  # Firebase versi terbaru (kompatibel Flutter 3.38)
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.1.0
  firebase_app_check: ^0.3.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/liang.jpg
    - assets/images/natsepa.jpg
    - assets/images/natsepa.jpeg
    - assets/images/benteng.jpg
    - assets/images/manusela.jpg
    - assets/images/paralayang.jpg
    
